title: Stackbit Personal Theme
baseURL: /
params:
  layout_type: boxed
  style: classic
  palette: red
  mode: light
  base_font: serif
  header:
    title: PORTOFOLIO
    logo: images/logo mdesign_Plan de travail 1.png
    logo_alt: Mon logo
    has_primary_nav: true
    primary_nav_links:
      - label: Portofolio
        url: /faq
        style: link
      - label: A propos
        url: /about
        style: link
      - label: Contactez moi
        url: /contact
        style: link
        icon_position: center
    has_secondary_nav: false
    has_anncmnt: false
  footer:
    logo: images/logo mdesign_Plan de travail 1.png
    logo_alt: Design logo
    has_primary_nav: true
    primary_nav_links:
      - label: About
        url: /about
        style: link
      - label: FAQ
        url: /faq
        style: link
      - label: Contact me
        url: /contact
        style: link
    has_secondary_nav: false
    secondary_nav_links:
      - label: Style Guide
        url: /style-guide
        style: link
      - label: Terms & Conditions
        url: /terms-conditions
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - label: Facebook
        url: 'https://www.facebook.com/'
        style: link
        has_icon: true
        icon: facebook
        icon_position: center
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/'
        style: link
        has_icon: true
        icon: instagram
        icon_position: center
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
  domain: 'https://cv-portfolio-61853.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
